name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: which ls
        run: which ls
      - name: which bash
        run: which bash
      - name: which sh
        run: which sh
      - name: which sh
        run: raku -e "shell 'ls'"
      - name: Install Dependencies
        run: zef install --/test --test-depends --deps-only .
      - name: Install App::Prove6
        run: zef install --/test App::Prove6
      - name: Build libsvm
        run: zef build .
      - name: Run Tests
        run: prove6 -l t
